name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voxel_${{ matrix.platform }}
          path: build
      - name: Download ${{ matrix.platform }} artifact
        uses: actions/download-artifact@v4
        with:
          name: voxel_${{ matrix.platform }}
          path: artifacts/voxel_${{ matrix.platform }}
      - name: Generate artifact name
        id: generate-name
        run: |
          echo "::set-output name=artifact::${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}.zip"
      - name: Upload ${{ matrix.platform }} to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifacts/voxel_${{ matrix.platform }}/${{ steps.generate-name.outputs.artifact }}
          asset_name: mything
          tag: latest
          overwrite: true
          body: "This is my release text"
