name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, windows]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        with:
          name: example
          preset: ${{ matrix.platform }}
          debugMode: "true"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: voxel_${{ matrix.platform }}
          path: build
      - name: Upload ${{ matrix.platform }} to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Godot-Voxel-Game/build/voxel_${{ matrix.platform }}.zip
          asset_name: mything
          tag: latest
          overwrite: true
          body: "This is my release text"
